Checkpoint 1
bshelkhonov/Space-Wars pull request #2
Opened 2020-04-07 08:58 UTC by bshelkhonov

Прошу @maked0n проверить Checkpoint 1

2020-04-07 22:10 UTC, alexmikhalevich requested changes
В целом все прекрасно. Два небольших замечания:
1. кода gtest в твоем репо явно быть не должно, зачем он тут? ты же вполне стандартный пакет используешь, а не какой-то свой кастомный форк
2. по какой логике ты именуешь заголовочные файлы с постфиксом hpp вместо h?

2020-04-08 06:26 UTC, bshelkhonov commented
По поводу gtest: я его устанавливаю локалько для проекта, поэтому добавил его в репозиторий. Про hpp, считаю, что дело вкуса.

2020-04-08 13:35 UTC, maked0n commented
> По поводу gtest: я его устанавливаю локалько для проекта

все еще не вижу причин хранить этот код в репозитории  
если хочется локально для проекта, то нужно завести скрипт, который будет выкачивать нужный релиз gtest при сборке и встроить этот скрипт в твою сборочную систему

> Про hpp, считаю, что дело вкуса.

ну так я и не возражаю, я просто хочу понять причину :)

2020-04-08 14:05 UTC, bshelkhonov commented
Кстати, а почему вы не возражаете насчёт хранения SFML в репозитории?

2020-04-08 14:21 UTC, maked0n commented
> Кстати, а почему вы не возражаете насчёт хранения SFML в репозитории?

конечно же, в этом случае ситуация полностью симметрична случаю с gtest  
я думал, что это будет очевидно :)

2020-04-08 15:19 UTC, bshelkhonov commented
Готово, убрал sfml и gtest

2020-04-08 15:25 UTC, alexmikhalevich approved these changes

2020-04-08 15:27 UTC, bshelkhonov commented
nice

2020-04-08 15:27 UTC, merged